<Project Sdk="Godot.NET.Sdk/4.5.1" InitialTargets="CheckDependencyPaths">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>true</ImplicitUsings>
        <Nullable>enable</Nullable> <!--Makes code analysis regarding null values stricter.-->
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <DefaultItemExcludes>packages/**</DefaultItemExcludes>
        <AppOutputBase>$(MSBuildProjectDirectory)\</AppOutputBase>
        <PathMap>$(AppOutputBase)=.\</PathMap>
        <PlatformTarget>AnyCPU</PlatformTarget> <!-- Added for cross-platform compatibility -->
    </PropertyGroup>

    <!-- OS Detection -->
    <PropertyGroup>
        <IsWindows>false</IsWindows>
        <IsLinux>false</IsLinux>
        <IsOSX>false</IsOSX>
        <IsWindows Condition="$([MSBuild]::IsOSPlatform('Windows'))">true</IsWindows>
        <IsLinux Condition="$([MSBuild]::IsOSPlatform('Linux'))">true</IsLinux>
        <IsOSX Condition="$([MSBuild]::IsOSPlatform('OSX'))">true</IsOSX>
    </PropertyGroup>

    <!-- // NOTE: Megadot is version 4.5.1, and the game won't load your .pck if the Godot version used is newer. -->

    <!-- Windows -->
    <PropertyGroup Condition="'$(IsWindows)' == 'true'">
        <AutoSteamPath>$(registry:HKEY_CURRENT_USER\Software\Valve\Steam@SteamPath)\steamapps</AutoSteamPath>
        <SteamLibraryPath Condition="Exists('$(AutoSteamPath)/common/Slay the Spire 2')">$(AutoSteamPath)</SteamLibraryPath>

        <GodotPath>D:\Slay The Spire 2 Modding\Megadot\MegaDot_v4.5.1-stable_mono_win64.exe</GodotPath>
        <!-- If on Windows and Slay the Spire 2 is not installed in your default steam library, adjust the following.-->
        <SteamLibraryPath Condition="'$(SteamLibraryPath)' == ''">D:\Steam\steamapps\common\Slay the Spire 2</SteamLibraryPath>

        <!-- The below should not need to be changed. -->
        <Sts2Path>$(SteamLibraryPath)/common/Slay the Spire 2</Sts2Path>
        <ModsPath>$(Sts2Path)/mods/</ModsPath>
        <Sts2DataDir>$(Sts2Path)/data_sts2_windows_x86_64</Sts2DataDir>
    </PropertyGroup>

    <!-- Linux -->
    <PropertyGroup Condition="'$(IsLinux)' == 'true'">
        <SteamLibraryPath>$(HOME)/.local/share/Steam/steamapps</SteamLibraryPath>
        <!-- Change the path here if using a downloaded binary instead of the Steam version-->
        <GodotPath>$(HOME)/.local/share/Steam/steamapps/common/Godot Engine/godot.x11.opt.tools.64</GodotPath>

        <!-- The below should not need to be changed. -->
        <Sts2Path>$(SteamLibraryPath)/common/Slay the Spire 2</Sts2Path>
        <ModsPath>$(Sts2Path)/mods/</ModsPath>
        <Sts2DataDir>$(Sts2Path)/data_sts2_linuxbsd_x86_64</Sts2DataDir>
    </PropertyGroup>

    <!-- macOS -->
    <PropertyGroup Condition="'$(IsOSX)' == 'true'">
        <SteamLibraryPath>$(HOME)/Library/Application Support/Steam/steamapps</SteamLibraryPath>
        <GodotPath>$(HOME)/Applications/Godot_mono.app/Contents/MacOS/Godot</GodotPath>

        <!-- The below should not need to be changed. -->
        <Sts2Path>$(SteamLibraryPath)/common/Slay the Spire 2</Sts2Path>
        <ModsPath>$(Sts2Path)/SlayTheSpire2.app/Contents/MacOS/mods/</ModsPath>
        <Sts2DataDir>$(Sts2Path)/SlayTheSpire2.app/Contents/Resources/data_sts2_macos_x86_64</Sts2DataDir>
    </PropertyGroup>

    <PropertyGroup>
        <!-- Diasble architecture mismatch warning; mods are ideally built for all platforms (MSIL)
             while your local StS2 version will be for your specific platform. -->
        <NoWarn>$(NoWarn);MSB3270</NoWarn>
    </PropertyGroup>

    <ItemGroup Condition="Exists('$(Sts2DataDir)')">
        <Reference Include="0Harmony">
            <HintPath>$(Sts2DataDir)/0Harmony.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="sts2">
            <HintPath>$(Sts2DataDir)/sts2.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>

    <ItemGroup Condition="Exists('$(ModsPath)LimbusCore')">
        <Reference Include="LimbusCore">
            <HintPath>$(ModsPath)LimbusCore/LimbusCore.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>
    
    <ItemGroup>
        <PackageReference Include="Alchyr.Sts2.BaseLib" Version="3.1.0" PrivateAssets="All" />
        <PackageReference Include="Alchyr.Sts2.ModAnalyzers" Version="0.1.9" />
        <AdditionalFiles Include="RienSang/localization/**/*.json"/>
        <PackageReference Include="Lib.Harmony" Version="2.4.2" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="RienSang/**"/>
        <Compile Remove="materials/**"/>
        <Compile Remove="shaders/**"/>
        <Compile Remove="images/**"/>
        <Compile Remove="zNoCompile\**" />
        <EmbeddedResource Remove="RienSang/**"/>
        <EmbeddedResource Remove="materials/**"/>
        <EmbeddedResource Remove="shaders/**"/>
        <EmbeddedResource Remove="images/**"/>
    </ItemGroup>
    
    <ItemGroup>
        <None Include=".gitignore"/>
        <None Include="RienSang.json"/>
        <None Include="project.godot"/>
        <None Include="RienSang/**"/>
        <None Include="RienSangCode\Nodes\NRiensang.cs" />
        <None Include="RienSangCode\Nodes\NRiensang.cs.uid" />
        <None Include="RienSangCode\Nodes\SmoothFollowCamera.cs.uid" />
        <None Include="RienSangCode\Nodes\XOnlyCameraTarget.cs.uid" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="RienSang\animation\" />
        <Folder Include="RienSang\images\card_portraits\" />
        <Folder Include="RienSang\images\packed\" />
        <Folder Include="RienSang\images\riensang\transitions\" />
        <Folder Include="RienSang\images\ui\combat\energy_counters\" />
        <Folder Include="RienSang\images\vfx\" />
        <Folder Include="RienSang\themes\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\LimbusCore\LimbusCore.csproj" />
    </ItemGroup>
    

    <Target Name="CheckDependencyPaths">
        <Error
                Text=" Slay the Spire 2 data not found at path '$(Sts2DataDir)'"
                Condition="'$(Sts2DataDir)' == '' or !Exists('$(Sts2DataDir)')"/>
        <Error
                Text=" Godot not found at path '$(GodotPath)'"
                Condition="'$(GodotPath)' == '' or !Exists('$(GodotPath)')"/>
    </Target>

    <Target Name="CopyToModsFolderOnBuild" AfterTargets="PostBuildEvent">
        <Message Text="Copying .dll and manifest to mods folder." Importance="high"/>
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ModsPath)$(MSBuildProjectName)/"/>
        <Copy SourceFiles="RienSang.json" DestinationFolder="$(ModsPath)$(MSBuildProjectName)/"/>
        <Message Text="Copying BaseLib to mods folder." Importance="high"/>
        <ItemGroup>
            <BaseLibFiles Include="packages/alchyr.sts2.baselib/**/lib/**/BaseLib.dll;packages/alchyr.sts2.baselib/**/Content/BaseLib.pck;packages/alchyr.sts2.baselib/**/Content/BaseLib.json;"/>
        </ItemGroup>
        <Copy SourceFiles="@(BaseLibFiles)" DestinationFolder="$(ModsPath)BaseLib/"/>
    </Target>

    <Target Name="GodotPublish" AfterTargets="Publish" Condition="'$(GodotPath)' != '' and Exists('$(GodotPath)') and '$(IsInnerGodotExport)' != 'true'">
        <Message Text="Exporting Godot .pck to mods folder" Importance="high"/>
        <Exec Command="&quot;$(GodotPath)&quot; --headless --export-pack &quot;BasicExport&quot; &quot;$(ModsPath)$(MSBuildProjectName)/$(MSBuildProjectName).pck&quot;"
              EnvironmentVariables="IsInnerGodotExport=true;MSBUILDDISABLENODEREUSE=1"
              ContinueOnError="WarnAndContinue"/>
    </Target>

    <Target Name="GodotPublishSkipped" AfterTargets="Publish" Condition="'$(GodotPath)' == '' or !Exists('$(GodotPath)')">
        <Message Text="Skipping Godot .pck export because GodotPath is not configured." Importance="high"/>
    </Target>
</Project>